# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MySmartWatch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  
  # Pods for MySmartWatch

  target 'MySmartWatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MySmartWatchUITests' do
    # Pods for testing
  end

end
